# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Gradio app files into the container
COPY main.py .

# Expose the port that Gradio app will be running on
EXPOSE 7860

# Command to start the Gradio app when the container starts
CMD ["python", "main.py"]